const state={sex:localStorage.getItem('become.sex')||'male',hair:localStorage.getItem('become.hair')||'bun',beard:localStorage.getItem('become.beard')||'full'};
const hairNames={short:'Court',long:'Longs',bun:'Chignon',ponytail:'Queue de cheval'};
const beardNames={none:'Aucune',stubble:'Naissante',short:'Courte',full:'Complète',long:'Longue'};
function img(src){const e=document.createElement('img');e.src=src;e.draggable=false;return e}
function renderCharacter(el){el.replaceChildren();el.append(img(`assets/base-${state.sex}.svg`),img(`assets/hair-${state.hair}.svg`));if(state.sex==='male'&&state.beard!=='none')el.append(img(`assets/beard-${state.beard}.svg`))}
function save(){localStorage.setItem('become.sex',state.sex);localStorage.setItem('become.hair',state.hair);localStorage.setItem('become.beard',state.beard)}
function render(){save();renderCharacter(document.querySelector('#character'));renderCharacter(document.querySelector('#preview'));document.querySelectorAll('[data-sex]').forEach(b=>b.classList.toggle('active',b.dataset.sex===state.sex));document.querySelector('#beardGroup').style.display=state.sex==='male'?'block':'none';
const hc=document.querySelector('#hairChoices');hc.replaceChildren();Object.entries(hairNames).forEach(([k,n])=>{const b=document.createElement('button');b.dataset.hair=k;b.className=state.hair===k?'active':'';b.textContent=n;hc.append(b)});
const bc=document.querySelector('#beardChoices');bc.replaceChildren();Object.entries(beardNames).forEach(([k,n])=>{const b=document.createElement('button');b.dataset.beard=k;b.className=state.beard===k?'active':'';b.textContent=n;bc.append(b)})}
document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelector('#'+p.dataset.page).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x===p));scrollTo(0,0);return}const s=e.target.closest('[data-sex]');if(s){state.sex=s.dataset.sex;render();return}const h=e.target.closest('[data-hair]');if(h){state.hair=h.dataset.hair;render();return}const b=e.target.closest('[data-beard]');if(b){state.beard=b.dataset.beard;render();return}});render();